### PR TITLE
Add NYC 311 data.

### LINKED ISSUE #39: Add NYC 311 data.
Use NYC's Socrata API to add their city's mobility-related issues to our database.

### PR DESCRIPTION
**Pull request by aelawson**
Adds script / modifies data collection routines to collect 311 data from NYC API in tandem with Boston/San Francisco.

@AlexMerritt does this look good to you? I did some testing locally and it seemed to function properly.

Resolves #39

### CODE REVIEW

**Comment by AlexMerritt** [comment]
@aelawson Ya this looks good. I am in the process of getting the mapping working. The only thing that needs to be changed is in the query statement. If you look in either of boston or sanfran you can see in the query I use $date when comparing against the date in the db. When the scheduler see this it will replace this keyword and replace it with the last time the data was checked. If you could make this change in the query statement for nyc that would be very helpful

**Comment by aelawson** [comment]
Oh yeah I forgot to change that. I just set the date temporarily because no data was coming back to test with - I'll set it to the $date variable that you mentioned.

**Comment by AlexMerritt** [comment]
So I changed how the 311 objects are created. I removed both SF311.js and Boston311.js. I created a new factory that makes the queries objects from a json file. If you want I can convert the NYC311.js to the new format unless you want to take a shot at it. The file is back-end/endpoints.json and all that would needed to be done is copied a previous entry and change the values.

**Comment by aelawson** [comment]
Sure, I'll do the conversion for the NYC one so I can get acquainted with it.

**Pull request merged**
